USE [master]
GO
/****** Object:  Database [Ejemplo2]    Script Date: 30/5/2024 10:14:59 ******/
CREATE DATABASE [Ejemplo2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Ejemplo2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Ejemplo2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Ejemplo2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Ejemplo2_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Ejemplo2] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Ejemplo2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Ejemplo2] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Ejemplo2] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Ejemplo2] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Ejemplo2] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Ejemplo2] SET ARITHABORT OFF 
GO
ALTER DATABASE [Ejemplo2] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Ejemplo2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Ejemplo2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Ejemplo2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Ejemplo2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Ejemplo2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Ejemplo2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Ejemplo2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Ejemplo2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Ejemplo2] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Ejemplo2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Ejemplo2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Ejemplo2] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Ejemplo2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Ejemplo2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Ejemplo2] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Ejemplo2] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Ejemplo2] SET RECOVERY FULL 
GO
ALTER DATABASE [Ejemplo2] SET  MULTI_USER 
GO
ALTER DATABASE [Ejemplo2] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Ejemplo2] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Ejemplo2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Ejemplo2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Ejemplo2] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Ejemplo2] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Ejemplo2', N'ON'
GO
ALTER DATABASE [Ejemplo2] SET QUERY_STORE = OFF
GO
USE [Ejemplo2]
GO
/****** Object:  Table [dbo].[Persona]    Script Date: 30/5/2024 10:14:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Persona](
	[PersonaID] [varchar](50) NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
	[Tipo] [tinyint] NOT NULL,
	[Gender] [varchar](10) NOT NULL,
	[Password] [varchar](100) NOT NULL
 CONSTRAINT [PK_Persona] PRIMARY KEY CLUSTERED 
(
	[PersonaID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PersonaRol]    Script Date: 30/5/2024 10:14:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PersonaRol](
	[PersonaID] [varchar](50) NOT NULL,
	[RolID] [int] NOT NULL,
 CONSTRAINT [PK_PersonaRol] PRIMARY KEY CLUSTERED 
(
	[PersonaID] ASC,
	[RolID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Rol]    Script Date: 30/5/2024 10:14:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Rol](
	[RolID] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Rol] PRIMARY KEY CLUSTERED 
(
	[RolID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Telefono]    Script Date: 30/5/2024 10:14:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Telefono](
	[TelefonoID] [int] IDENTITY(1,1) NOT NULL,
	[PersonaID] [varchar](50) NOT NULL,
	[Telefono] [varchar](15) NOT NULL,
 CONSTRAINT [PK_Telefono] PRIMARY KEY CLUSTERED 
(
	[TelefonoID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PersonaRol]  WITH CHECK ADD  CONSTRAINT [FK_PersonaRol_Persona] FOREIGN KEY([PersonaID])
REFERENCES [dbo].[Persona] ([PersonaID])
GO
ALTER TABLE [dbo].[PersonaRol] CHECK CONSTRAINT [FK_PersonaRol_Persona]
GO
ALTER TABLE [dbo].[PersonaRol]  WITH CHECK ADD  CONSTRAINT [FK_PersonaRol_Rol] FOREIGN KEY([RolID])
REFERENCES [dbo].[Rol] ([RolID])
GO
ALTER TABLE [dbo].[PersonaRol] CHECK CONSTRAINT [FK_PersonaRol_Rol]
GO
ALTER TABLE [dbo].[Telefono]  WITH CHECK ADD  CONSTRAINT [FK_Telefono_Persona] FOREIGN KEY([PersonaID])
REFERENCES [dbo].[Persona] ([PersonaID])
GO
ALTER TABLE [dbo].[Telefono] CHECK CONSTRAINT [FK_Telefono_Persona]
GO
USE [master]
GO
ALTER DATABASE [Ejemplo2] SET  READ_WRITE 
GO
