// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using PersonasService.Models;
//
//    var genderInformation = GenderInformation.FromJson(jsonString);

namespace PersonasService.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class GenderInformation
    {
        [JsonProperty("count")]
        public long Count { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("gender")]
        public string Gender { get; set; }

        [JsonProperty("probability")]
        public long Probability { get; set; }
    }

    public partial class GenderInformation
    {
        public static GenderInformation FromJson(string json) => JsonConvert.DeserializeObject<GenderInformation>(json, PersonasService.Models.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this GenderInformation self) => JsonConvert.SerializeObject(self, PersonasService.Models.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
